### ISSUE TITLE
Alle Strings die der Nutzer sieht in strings.xml definieren

### ISSUE THREAD

**Issue by RaphaelNeubert** [RaphaelNeubert/I5_GPS_Tracks#116]

**Comment by RaphaelNeubert** [comment]
in ListingTracks muss das switch case warscheinlich zu if, else umgewandelt werden.
Strings holt man sich aus strings.xml mit getString(R.string.<stringname>);

**Comment by qduyp** [comment]
`if(String.valueOf(item).equals(getString( R.string.details)))
                {

                }

                else if(String.valueOf(item).equals(getString( R.string.showTrack)))
                {
                    Intent intent = new Intent();
                    intent.putExtra("optionClicked", String.valueOf(item));
                    intent.putExtra("fileName", selectedItem);

                    setResult(Activity.RESULT_OK, intent);
                    finish();
                }

                else if (String.valueOf(item).equals(getString( R.string.edit)))
                {

                }

                else if(String.valueOf(item).equals(getString( R.string.rename)))
                {
                    File newName=new File(dir,"UPDATED_FILE_"+selectedItem);
                    file.renameTo(newName);
                    //  recreate();
                    finish();
                    overridePendingTransition(10, 10);
                    startActivity(getIntent());
                    overridePendingTransition(10, 10);
                }

                else if (String.valueOf(item).equals(getString( R.string.contRec)))
                {

                }

                else if (String.valueOf(item).equals(getString( R.string.delete)))
                {
                    file.delete();
                    finish();
                    overridePendingTransition(10, 10);
                    startActivity(getIntent());
                    overridePendingTransition(10, 10);
                }
`

so hier sind alle ListingTrack als if else umgewandelt. Ist das richtig? und dann, muss ich alle String  in strings.xml definieren?

**Comment by qduyp** [comment]
![image](https://user-images.githubusercontent.com/92373381/169360654-aeec3b0b-a5b0-4aa0-a601-1686f40b5f27.png)
Sprache der App ist jetzt als Default-Sprache des Handys. Aber es gibt noch ein bug, dass "Track umbenennen" auf Deutsch bleibt. Ich habe keine Ahnung. Ich gucke noch mal.
Ich habe noch eine Frage. Wo gibt es noch Strings, die der Nutzter sehen kann? Steht alles nur in ListingTrack oder?
