### ISSUE TITLE
UC01 Diagramm inkludieren

### ISSUE THREAD

**Issue by FlexFlux1** [RaphaelNeubert/I5_GPS_Tracks#16]
Kriege das UC01 Diagramm nicht inkludiert, es liegt unter "docs" --> "architecture" --> "images".
Hab den include unter den Text zu UC01 gelegt, er zeigt das aber fehlerhaft an leider und ich weiß nicht was das Problem ist

**Comment by RaphaelNeubert** [comment]
Der Grund fuer das Problem war ein Tippfehler bei der benennung der Datei. Die Datei hiess ...01_ I5..., aber includiert hast du ...01_I5 (kein Leerzeichen). Desweiteren musste ich das Bild noch nach .../requirements/images kopieren. Es macht Sinn, dass das Bild auch in .../architecture/images ist, aber alle Bilder die in .../requirements verwendet werden, sollten auch in .../requirements/images liegen sonst koennte es verwirrend werden.
