### ISSUE TITLE
Benutzerumgebung

### ISSUE THREAD

**Issue by RaphaelNeubert** [RaphaelNeubert/I5_GPS_Tracks#66]
Siehe kommentar: 1.3.2

**Comment by RaphaelNeubert** [comment]
Anschliessend ueberpruefen ob der Zusammenhang von Bedarf und Benutzerumgebung stimmt. ggf. Bedarfe anpassen

**Comment by lschoenthier** [comment]
Noch zu klären:
Wann nimmt man Tracks auf?
Zu welchem Zweck?
Gibt es noch mehr Fehler als nicht abfahrbare Routen?
Wie findet Zuordnung von Smartphone und Roboter statt?
