### ISSUE TITLE
Befassung mit dem Dateisystem.

### ISSUE THREAD

**Issue by RaphaelNeubert** [RaphaelNeubert/I5_GPS_Tracks#83]
> Wie koennen wir Dateien an bestimmte Stellen speichern. (Permissions??)
> Items der GPS-Track-Auflistung aus Dateien die sich im Ordner befinden erstellen (Momentan sind es einfach teststrings).
> Loeschen von Items der Auflistung (der Dateien in dem Ordner)
> Umbenennen von Tracks

**Comment by Alexandr-Pronin** [comment]
**Permission in manifest.xm**l:
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
 <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
 
 **Dateien  an Device** : Device File Explorer -> data -> *.gps_tracks -> files

**Comment by Alexandr-Pronin** [comment]
Es fehlt noch Internal Testing
 @lschoenthier wollen wir das zusammen  gucken?

**Comment by lschoenthier** [comment]
jo
