### ISSUE TITLE
Bei wechsel von Menues wird die Kameraposition resetet

### ISSUE THREAD

**Issue by RaphaelNeubert** [RaphaelNeubert/I5_GPS_Tracks#84]
Bei wechsel von Menues wird die Kameraposition resetet und wird erst nach 2sec wieder auf den aktuellen Standorwert gesetzt.
Kann durch die Funktionen onResume und onPause behoben werden indem onPause der letzte bekannte Standort gespeichert wird
und anschliessend in onResume die Kamera auf diesen gesetzt wird.

**Comment by qduyp** [comment]
es gibt auch ein gleiche Problem bei App-Startup. Ich denke, das Problem in Funktion onCreate liegt, weil setCenter ein bestimmter Punkt ist. Kann das als einen aktuelle Standort bei Startup setzen?

**Comment by RaphaelNeubert** [comment]
Stimmt. Das Problem ist warscheinlich das es immer einen Moment dauert bis der aktuelle Standort ermittelt wurde.
Ursprünglich hat man immer erst die gesammte Weltkarte gesehen und dann nach 2 Sekunden ist man erst auf den aktuellen
Standort gesprungen. Vielleicht findest du auf Google eine gute lösung dafür. Man könnte natürlich beim Schließen der App den zuletzt bekannten Standort speichern und den dann als Startwert nehmen, aber vielleicht gibt es auch eine bessere Lösung.

**Comment by qduyp** [comment]
Ich habe deine Solution probiert, aber es geht nicht, und ich habe keine Ahnung, wie dieses Problem geloest wird. Unter ist Code.
`    Override
    public void onResume() {
        super.onResume();
        //this will refresh the osmdroid configuration on resuming.
        //if you make changes to the configuration, use
        //SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);
        //Configuration.getInstance().load(this, PreferenceManager.getDefaultSharedPreferences(this));
        if (pauseLocation != null){ 
            map.getController().animateTo(new GeoPoint(pauseLocation.getLatitude(), pauseLocation.getLongitude()));
        }
        else {
            map.getController().animateTo(new GeoPoint(51.0374,13.7638));   

        }
        map.onResume(); //needed for compass, my location overlays, v6.0.0 and up
    }

    Override
    public void onPause() {
        super.onPause();
        //this will refresh the osmdroid configuration on resuming.
        //if you make changes to the configuration, use
        //SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);
        //Configuration.getInstance().save(this, prefs);
        pauseLocation = locationOverlay.getLastFix();
        map.onPause();  //needed for compass, my location overlays, v6.0.0 and up
    }`

**Comment by qduyp** [comment]
Viellect wird den Standortwert nicht im pauseLoction gespeichert. Wie kann man die Koordinaten-Information auf die Karte zeigen? Ich habe Marker-setTextIcon verwendet, und die App instant crash

**Comment by RaphaelNeubert** [comment]
Sieht eigentlich gut aus. Du koenntest versuchen statt getLastFix() die Funktion getMyLocation() verwenden siehe: 
https://osmdroid.github.io/osmdroid/javadocAll/org/osmdroid/views/overlay/mylocation/MyLocationNewOverlay.html#getMyLocation--
Wie man einen Marker plottet findest du in der MainActivity auf Zeile 103-107.
Zum debuggen kannst du die Funktion Log.i(<tag>,<msg>) verwenden.

**Comment by qduyp** [comment]
pauseLocation steht in Log-Datei, aber der Standortwert von der Funktion onPause return als null in die Funktion onResume. ich declarieren pauseLocation als ein globales GeoPoint-Variable.
was denkst du? hast du eine Idee?

**Comment by RaphaelNeubert** [comment]
Ich schaue es mir heute abend mal an. Wenn ich mich richtig erinnere hatte ich ein aehnliches Problem auch schon mal
mit dem locationOverlay.

**Comment by RaphaelNeubert** [comment]
Ich habe eine kleine Aenderung in der Klasse ListingActivity gemacht.  
Siehe 6b5b5dbbf391ffc747d25c583e732b5ab1489e9b (auf dem dev branch)

Ich glaube das Problem war das es immer eine neute MainActivity erzeugt hat anstatt die existierende fortzusetzen.

Versuche das ganze jetzt mal mit deinem Code.

**Comment by RaphaelNeubert** [comment]
Anscheinend hat meine kleine aenderung das Problem schon behoben ohne das man irgendwas in onPause oder onResume
schreiben muss. Teste es am besten nochmal und oeffne das issue nochmal falls das nicht der fall sein sollte.

**Comment by qduyp** [comment]
@RaphaelNeubert ich habe noch mal getestet und alles läuft gut
